services:
  analysis-env:
    image: csuche/airline-customer-satisfaction-predictor:1e93de6
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64