services:
  analysis-env:
    image: csuche/airline-customer-satisfaction-predictor:a8e894c
    ports:
      - "8888:8888"
    volumes:
      - .:/home/joyvan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64