services:
  analysis-env:
    image: csuche/airline-customer-satisfaction-predictor:f8bee1c
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan
    deploy:
      resources:
        limits:
          memory: 5G
    platform: linux/amd64