name: dsci522-airline-pred
channels:
  - conda-forge
dependencies:
  - ipykernel=6.16
  - matplotlib=3.7
  - numpy=1.24
  - pandas=1.5
  - python=3.11
  - scikit-learn=1.3.2
  - seaborn=0.13.2
  - conda-lock=2.5.7
  - jupyterlab=4.0.5
  - pandera=0.7.1  
