name: dsci522-airline-pred
channels:
  - conda-forge
dependencies:
  - ipykernel
  - matplotlib
  - numpy=1.22
  - pandas=1.3
  - python=3.11
  - scikit-learn=1.3.2
  - seaborn=0.13.2
  - conda-lock=2.5.7