name: dsci522-airline-pred
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - matplotlib
  - numpy=1.22
  - pandas=1.3
  - python=3.9
  - category_encoders
  - scikit-learn
  - seaborn